### ISSUE TITLE
(not) recommended tools

### ISSUE THREAD

**Issue by DanielRuf** [virajkulkarni14/WebDeveloperSecurityChecklist#5]
I am missing recommendations about tools like "do not use FileZilla or another client/tool which stores credentials in cleartext / unencrypted".

Or did I oversee this and this is mentioned?

Personally I question a bit the backup checklist. If possible create offsite backups and never save them on the same server. Have a daily backup plan and do not store the credentials for the backup process on the server. …

**Comment by virajkulkarni14** [comment]
@DanielRuf thanks for this good suggestion. @mobrien, your thoughts on this? Should we create a new section based on the above recommendation?

**Comment by mobrien** [comment]
Can you flesh out your thoughts a bit more. What credentials do you mean and why FileZilla?

There is a point already about using a key store?

Regarding backups, I would never consider backups to be backups if they are on the same server!  Backups themselves are not part of security per se. But compromised backups are. So we should not be advocating for good ops practices like backups, but rather focus on how to ensure the backups are secure. The 2nd sentence about credentials should be covered by the key store recommendation. Perhaps we could make that more explicit?

**Comment by DanielRuf** [comment]
>There is a point already about using a key store?

Right. But not all tools use the keychain or a key store by default like Cyberduck, PhpStorm and other tools do.

So far FileZilla stores the passwords as base64 encoded strings if they are saved. Best would be: store all passwords in key stores and keychains and prevent tools which store passwords.

The current list of you mentions the key store under "database" but this is not enough ;-)

**Comment by mobsense** [comment]
Ah, you are referring to dev time key store. I was referring to run-time key store.

**Comment by virajkulkarni14** [comment]
@DanielRuf, any final points on this? @mobrien, how should I phrase the point about a developer keystore? I can close this issue if both of you let me know. Thanks 🙂

**Comment by DanielRuf** [comment]
Good question. I probably have not the same style like you have but probably there are some parts which could lead you for a good and short phrase.

> Use a local (offline) password manager like KeePass, KeePassX or another one (should be more secure).
> 
> Encrypt and store local credentials (FTP, SSH and so on) in the keychain / password store of your operating system.
> 
> Avoid tools (FTP / SSH clients, IDEs and so on) which do not support one of these solutions.

**Comment by DanielRuf** [comment]
Bump.
