### ISSUE TITLE
place all data in a single page

### ISSUE THREAD

**Issue by morajabi** [virajkulkarni14/WebDeveloperSecurityChecklist#6]
It's hard to discover and read all of data by switching pages. Please add all data to README with an index at top (you have one already).

It's better as with `xxxx-awesome` repos we see the same thing.

**Comment by virajkulkarni14** [comment]
I have created and merged [this pull request](https://github.com/virajkulkarni14/WebDeveloperSecurityChecklist/pull/7) thanks to your suggestion. 🙂
