### ISSUE TITLE
Use centralized logging for all services

### ISSUE THREAD

**Issue by mirkods** [virajkulkarni14/WebDeveloperSecurityChecklist#8]
Hi guys,
first of all congratulations for the great article on medium.
I have no experiencies in this argument so I'd like to know which stack/software is used to centralize logging. 
In my case I use nodejs but probably the logging centralization is agnostic to the technology.

Mirko

**Comment by mobsense** [comment]
I posted an answer on medium - repeated here:

There are a range of commercial products: loggly, logentries, elastic search.

We use an unreleased feature in our SenseDeep agent that does log capture and then stores on AWS S3. It is built into our SenseDeep agent. We looked at several of the commercial log capture products and their agents were all HUGE (> 50MB) and written in scripting languages. We wanted something very, very small and efficient. Our agent is < 4MB and extremely fast.

This log capture feature will be rolled out to customers later this year.

I’d like to chat more about hour requirements. Can you DM me: mob AT sensedeep.com?
